#!/usr/bin/env python
import argparse
from mdcheck import main
import sys
from pathlib import Path

class UnsupportedFormatError(ValueError):
    """File extension not in allowed list."""
    pass

def validate_file(filepath: str):

    filepath = Path(filepath)
    
    # Check extension
    if not filepath.suffix.lower() == '.nc':
        raise UnsupportedFormatError(
            f"Input file must be a netCDF file.\n{filepath.name} has extension '{filepath.suffix}' (expected: .nc)"
        )


if __name__ == '__main__':

    parser = argparse.ArgumentParser(
    description='Check metadata compliance with MET specifications')

    parser.add_argument('input_file',
                        type=str,
                        default=None,
                        help="input file, must be a netCDF file")
    
    try:
        args = parser.parse_args()
        validate_file(args.input_file)
    except UnsupportedFormatError as e:
        print(f'Error: {e}')
        sys.exit()
    except:
        parser.print_help()
        sys.exit()

    main(args)