#!/usr/bin/env python
import argparse
from mdcheck import main
import sys

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
    description='Check metadata compliance with MET specifications')

    parser.add_argument('input_file',
                        type=str,
                        default=None,
                        help="input file, must be a netCDF file")
    
    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        sys.exit()

    main(args)